---
version: "3.7"

services:
  postgres:
    hostname: postgres
    image: postgres:13.1
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:${PGPORT:-5432}

volumes:
  postgres-data:

networks:
  default:
    driver: bridge
